"""
Django settings for nadorex project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from django.conf.global_settings import EMAIL_HOST_PASSWORD
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-8=xld8bdea%k_m3_byvwy&h##)!28p)*-kdxa@ly=b&qr-r!hi'
SECRET_KEY = os.getenv("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media' 
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 465
# EMAIL_HOST_USER ='appnadorex@gmail.com'
# EMAIL_HOST_PASSWORD = 'utfl cmpr rpha qjpj'
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = True
# DEFUALT_FROM_EMAIL = EMAIL_HOST_USER
DEBUG = True
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' 
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_HOST_USER =os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
DEFUALT_FROM_EMAIL = os.getenv("DEFUALT_FROM_EMAIL")


ALLOWED_HOSTS = []


#Application definition
import pymysql
pymysql.install_as_MySQLdb()

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
    'cloudinary_storage',
    'cloudinary',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nadorex.urls'
'''
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.inject_translations',
 
            ],
        },
    },
]
'''
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.inject_translations',
            ],
        },
    },
]
WSGI_APPLICATION = 'nadorex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         # 'NAME': 'testdatabases',
#         'NAME': 'nadorex',
#         'USER': 'root',
#         'PASSWORD': '1qazxsw2',
#         'HOST': 'localhost',
#         'PORT': '3306',
        
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }



DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL")
    ),
    "old_mysql": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("OLD_DB_NAME"),
        "USER": os.getenv("OLD_DB_USER"),
        "PASSWORD": os.getenv("OLD_DB_PASSWORD"),
        "HOST": os.getenv("OLD_DB_HOST"),
        "PORT": os.getenv("OLD_DB_PORT", "3306"),
    }
    
}

# Internal Database URL= postgresql://nadorex_user:GCVwiWtM64dy1mbf6gHGM9P7Ssrzt1lx@dpg-d9vi0q37uimc73f4cdug-a/nadorex

# External Database URL=postgresql://nadorex_user:GCVwiWtM64dy1mbf6gHGM9P7Ssrzt1lx@dpg-d9vi0q37uimc73f4cdug-a.frankfurt-postgres.render.com/nadorex
# PSQL Command=PGPASSWORD=GCVwiWtM64dy1mbf6gHGM9P7Ssrzt1lx psql -h dpg-d9vi0q37uimc73f4cdug-a.frankfurt-postgres.render.com -U nadorex_user nadorex
#################
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
CORS_ALLOWED_ORIGINS =[
    "http://localhost:8000",
    "http://localhost:5176",
]
'''
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5177",
    "http://127.0.0.1:5177",
]
'''
CORS_ALLOW_CREDENTIALS =True
#CORS_ALLOW_ALL_ORIGINS = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

######STATIC_URL = 'static/'
STATIC_URL = '/static/'  # لازم يكون فيه سلاش في البداية والنهاية
STATIC_ROOT = '/static/'

LOGIN_URL = 'register'

# إضافة هذا السطر مهم جداً ليعرف Django من وين يجيب الملفات الثابتة
STATICFILES_DIRS = [
    BASE_DIR / "products" / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# ================================
# Logging setup (لإظهار رسائل debug في الكونسول)
# ================================
import logging

LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',  # يمكنك تغييره إلى INFO أو ERROR إذا أردتِ تقليل التفاصيل
    },
}
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# لمنع المتصفح من حظر الكوكيز أثناء استخدام http المحلي (Localhost)
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), # تم زيادة العمر إلى يوم كامل
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
}
# DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}