# Generated by Django 5.2.4 on 2026-06-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutoDeliveryLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auto_delivery_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'buyer_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerTranslations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ar', models.CharField(blank=True, max_length=255, null=True)),
                ('en', models.CharField(blank=True, max_length=255, null=True)),
                ('tr', models.CharField(blank=True, max_length=255, null=True)),
                ('de', models.CharField(blank=True, max_length=255, null=True)),
                ('fr', models.CharField(blank=True, max_length=255, null=True)),
                ('es', models.CharField(blank=True, max_length=255, null=True)),
                ('zh', models.CharField(blank=True, max_length=255, null=True)),
                ('ja', models.CharField(blank=True, max_length=255, null=True)),
                ('ko', models.CharField(blank=True, max_length=255, null=True)),
                ('sv', models.CharField(blank=True, max_length=255, null=True)),
                ('it', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'buyer_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('translation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'category_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Merchants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('merchant_lang', models.CharField(blank=True, max_length=10, null=True)),
                ('iyzico_merchant_key', models.CharField(blank=True, max_length=255, null=True)),
                ('iyzico_sub_key', models.CharField(blank=True, max_length=255, null=True)),
                ('submerchanttype', models.CharField(blank=True, db_column='subMerchantType', max_length=50, null=True)),
                ('gsmnumber', models.CharField(blank=True, db_column='gsmNumber', max_length=20, null=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('taxnumber', models.CharField(blank=True, db_column='taxNumber', max_length=50, null=True)),
                ('identitytype', models.CharField(blank=True, db_column='identityType', max_length=50, null=True)),
                ('identitynumber', models.CharField(blank=True, db_column='identityNumber', max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='zipCode', max_length=20, null=True)),
                ('iyzico_status', models.CharField(blank=True, max_length=50, null=True)),
                ('store_banner', models.CharField(blank=True, max_length=255, null=True)),
                ('store_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('store_description', models.TextField(blank=True, null=True)),
                ('description_color', models.CharField(blank=True, max_length=20, null=True)),
                ('description_font', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'merchants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price_at_order_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('log_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('return_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'order_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('return_status', models.CharField(blank=True, max_length=50, null=True)),
                ('return_days', models.IntegerField(blank=True, null=True)),
                ('book_language', models.CharField(blank=True, max_length=10, null=True)),
                ('chosen_color', models.CharField(blank=True, max_length=50, null=True)),
                ('chosen_size', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_company_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderShipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('shipping_status', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_shipments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_column='category', max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('date_requested', models.DateTimeField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'product_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_email', models.CharField(max_length=255)),
                ('rating', models.JSONField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('base_image', models.ImageField(upload_to='products/base/')),
                ('uses_mask', models.BooleanField(default=False)),
                ('mask_image', models.ImageField(blank=True, null=True, upload_to='products/masks/')),
                ('base_color_type', models.CharField(choices=[('neutral', 'Neutral'), ('single', 'Single'), ('dark', 'Dark/Patterned')], default='single', max_length=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('describtion', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_email', models.CharField(blank=True, max_length=255, null=True)),
                ('category_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('books_language', models.CharField(blank=True, max_length=10, null=True)),
                ('sizes', models.TextField(blank=True, null=True)),
                ('colors', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductsTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text_key', models.CharField(max_length=255, unique=True)),
                ('arabic', models.TextField()),
                ('english', models.TextField()),
                ('turkish', models.TextField()),
                ('german', models.TextField()),
                ('french', models.TextField()),
                ('spanish', models.TextField()),
                ('chinese', models.TextField()),
                ('japanese', models.TextField()),
                ('korean', models.TextField()),
                ('swedish', models.TextField()),
                ('italian', models.TextField()),
            ],
            options={
                'db_table': 'products_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTranslations',
            fields=[
                ('pk', models.CompositePrimaryKey('product_id', 'language_code', blank=True, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('language_code', models.CharField(max_length=10)),
                ('translated_name', models.CharField(blank=True, max_length=255, null=True)),
                ('translated_description', models.TextField(blank=True, null=True)),
                ('translated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('translated_old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'product_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestTranslations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('translated_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'request_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('supported_countries', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shipping_companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_key', models.CharField(max_length=255)),
                ('arabic', models.TextField()),
                ('english', models.TextField()),
                ('turkish', models.TextField()),
                ('german', models.TextField(blank=True, null=True)),
                ('french', models.TextField(blank=True, null=True)),
                ('spanish', models.TextField(blank=True, null=True)),
                ('chinese', models.TextField(blank=True, null=True)),
                ('japanese', models.TextField(blank=True, null=True)),
                ('korean', models.TextField(blank=True, null=True)),
                ('swedish', models.TextField(blank=True, null=True)),
                ('italian', models.TextField()),
                ('category_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/colors/')),
                ('is_available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.products')),
            ],
            options={
                'db_table': 'product_images',
            },
        ),
    ]
