# Generated by Django 5.2.6 on 2026-06-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchants',
            options={'managed': True},
        ),
    ]
