# Generated by Django 5.2.4 on 2026-06-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_merchants_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchants',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True},
        ),
    ]
