# Generated by Django 5.2.6 on 2026-06-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_merchants_options_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False},
        ),
    ]
