# Generated by Django 5.2.4 on 2026-07-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariants_barcode_productvariants_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='color_hex',
            field=models.CharField(blank=True, help_text='Hex color مثل #FF5733', max_length=7, null=True),
        ),
    ]
