# Generated by Django 5.2.4 on 2026-08-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('boolean', 'Boolean'), ('color', 'Color')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'category_attributes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoryAttributeOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'category_attribute_options',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'product_attributes',
                'managed': False,
            },
        ),
    ]
