# Generated by Django 5.2.4 on 2026-08-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_categoryattribute_categoryattributeoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttributeOptionTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10)),
                ('translation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category_attribute_option_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryAttributeTranslation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10)),
                ('translation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category_attribute_translations',
                'managed': False,
            },
        ),
    ]
