# Generated by Django 5.2.6 on 2026-08-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_categoryattributeoptiontranslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_values', to='products.categoryattribute')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_values', to='products.categoryattributeoption')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.productvariants')),
            ],
            options={
                'db_table': 'product_variant_attributes',
            },
        ),
    ]
