# Generated by Django 5.2.4 on 2026-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productvariantattributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', 'New Order'), ('order_cancelled', 'Order Cancelled'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('return_requested', 'Return Requested')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='categoryattribute',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='categoryattributeoption',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='productvariantattributes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
